[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
avalanche = "${AVALANCHE_RPC_URL}"

[etherscan]
avalanche = { key = "${SNOWTRACE_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true